server:
  port: 8090
spring:
  data:
    mongodb:
      username: charlotte3517
      password: charlotte3517
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin